const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const logger = require('../utils/logger');

// --- KONFIGURASI PATH ---
const NGINX_VPATCH_FILE = '/etc/nginx/cyberx-vpatch.conf';
const APACHE_DIR = process.env.PROTECTED_DIR || '/var/www/html';
const APACHE_HTACCESS = `${APACHE_DIR}/.htaccess`;

// --- FUNGSI BACKUP AMAN ---
const backupFile = (filePath) => {
    if (fs.existsSync(filePath)) {
        const backupPath = `${filePath}.bak_${Date.now()}`;
        fs.copyFileSync(filePath, backupPath);
        logger.info(`[VPATCH] Backup dibuat: ${backupPath}`);
    }
};

const handleVirtualPatch = async (msg, type) => {
    const serverType = type.toLowerCase().trim();

    if (!['nginx', 'apache', 'nodejs'].includes(serverType)) {
        return msg.reply('⚠️ *Format Perintah Salah!*\nGunakan: `!vpatch nginx`, `!vpatch apache`, atau `!vpatch nodejs`');
    }

    await msg.reply(`⏳ *Menempa Perisai WAF untuk ${serverType.toUpperCase()}...*\nSistem sedang mengompilasi dan menerapkan aturan keamanan...`);

    // ==========================================
    // 1. VIRTUAL PATCH: NGINX
    // ==========================================
    if (serverType === 'nginx') {
        const nginxRules = `
# ======================================================================
# CYBER-X NGINX WAF (WEB APPLICATION FIREWALL)
# GENERATED BY SYSTEM - DO NOT EDIT MANUALLY
# ======================================================================

# 1. BLOKIR FILE SENSITIF & KONFIGURASI HIDDEN
location ~ /\\.(env|git|svn|log|bak|ini|conf|sql|sh)$ {
    deny all;
    access_log off;
    log_not_found off;
}

# 2. BLOKIR EKSEKUSI SCRIPT JAHAT DI FOLDER UPLOAD
location ~* /(uploads|images|assets|media|tmp)/.*\\.(php|php3|php4|php5|pl|py|jsp|asp|sh|cgi)$ {
    deny all;
}

# 3. BLOKIR SCANNER & BAD BOTS
if ($http_user_agent ~* (nikto|sqlmap|acunetix|dirbuster|nmap|zmeu|masscan|scan|grabber|curl|wget)) {
    return 403;
}

# 4. BLOKIR XSS (CROSS-SITE SCRIPTING)
if ($query_string ~* "(<|%3C).*script.*(>|%3E)|(javascript:|vbscript:)") {
    return 403;
}

# 5. BLOKIR SQL INJECTION (SQLi)
if ($query_string ~* "(UNION\\s+SELECT|CONCAT|WAITFOR\\s+DELAY|SELECT\\s+.*\\s+FROM|UPDATE\\s+.*\\s+SET|DROP\\s+TABLE|INSERT\\s+INTO)") {
    return 403;
}

# 6. BLOKIR PATH TRAVERSAL & LOCAL FILE INCLUSION (LFI)
if ($query_string ~* "(etc/passwd|boot\\.ini|\\.\\./\\.\\./|windows/win\\.ini)") {
    return 403;
}

# 7. MATIKAN DIRECTORY LISTING
autoindex off;
`;
        try {
            backupFile(NGINX_VPATCH_FILE);
            fs.writeFileSync(NGINX_VPATCH_FILE, nginxRules);
            
            // PRE-FLIGHT CHECK: Cek apakah Nginx Typo/Error sebelum Reload
            exec('nginx -t', (testErr, testStdout, testStderr) => {
                if (testErr || testStderr.includes('failed')) {
                    logger.error(`[VPATCH-NGINX] Uji syntax gagal: ${testStderr}`);
                    return msg.reply(`❌ *Sintaks Nginx Gagal!*\nAturan keamanan tidak diterapkan karena bentrok dengan konfigurasi Nginx Anda. Cek log server.`);
                }

                // Jika aman, lakukan Reload Nginx
                exec('systemctl reload nginx', (reloadErr) => {
                    if (reloadErr) {
                        logger.error(`[VPATCH-NGINX] Gagal reload: ${reloadErr.message}`);
                        return msg.reply(`❌ *Gagal mereload Nginx:* ${reloadErr.message}`);
                    }
                    
                    const report = `
✅ *VIRTUAL PATCH NGINX AKTIF!* 🛡️

Perisai telah ditegakkan. Filter yang diaktifkan:
• Anti File Sensitif (.env, .git)
• Anti Eksekusi Shell (Uploads Dir)
• Anti Bad Bots & Scanner (Nmap, Nikto)
• Anti SQL Injection & XSS
• Anti Path Traversal (LFI/RFI)

_Pastikan "include ${NGINX_VPATCH_FILE};" sudah ada di blok server konfigurasi web Anda._`.trim();
                    
                    logger.info('[VPATCH] Nginx WAF sukses diterapkan.');
                    msg.reply(report);
                });
            });
        } catch (error) {
            logger.error(`[VPATCH-NGINX] Gagal menulis file: ${error.message}`);
            msg.reply('❌ *Terjadi kesalahan saat menulis konfigurasi Nginx.*');
        }
    }

    // ==========================================
    // 2. VIRTUAL PATCH: APACHE
    // ==========================================
    else if (serverType === 'apache') {
        const apacheRules = `
# BEGIN CYBER-X WAF
<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # 1. BLOKIR FILE SENSITIF
    RewriteCond %{REQUEST_URI} \\.(env|git|svn|log|bak|ini|conf|sql|sh)$ [NC]
    RewriteRule ^.*$ - [F,L]
    
    # 2. BLOKIR EKSEKUSI SCRIPT DI UPLOADS
    RewriteCond %{REQUEST_URI} ^/(uploads|images|assets|media|tmp)/ [NC]
    RewriteCond %{REQUEST_URI} \\.(php|php3|php4|php5|pl|py|jsp|asp|sh|cgi)$ [NC]
    RewriteRule ^.*$ - [F,L]
    
    # 3. BLOKIR BAD BOTS & SCANNER
    RewriteCond %{HTTP_USER_AGENT} (nikto|sqlmap|acunetix|dirbuster|nmap|zmeu|masscan|scan|grabber) [NC]
    RewriteRule ^.*$ - [F,L]
    
    # 4. BLOKIR SQLi, XSS, & LFI DI QUERY STRING
    RewriteCond %{QUERY_STRING} (<|%3C).*script.*(>|%3E) [NC,OR]
    RewriteCond %{QUERY_STRING} (UNION\\s+SELECT|CONCAT|WAITFOR\\s+DELAY|SELECT\\s+.*\\s+FROM) [NC,OR]
    RewriteCond %{QUERY_STRING} (etc/passwd|boot\\.ini|\\.\\./\\.\\./) [NC]
    RewriteRule ^.*$ - [F,L]
    
    # 5. MATIKAN DIRECTORY LISTING
    Options -Indexes
</IfModule>
# END CYBER-X WAF
`;
        try {
            // Cek apakah direktori target ada
            if (!fs.existsSync(APACHE_DIR)) {
                return msg.reply(`❌ Direktori Apache tidak ditemukan di \`${APACHE_DIR}\`.\nPastikan variabel PROTECTED_DIR di .env sudah benar.`);
            }

            let htaccessContent = '';
            if (fs.existsSync(APACHE_HTACCESS)) {
                backupFile(APACHE_HTACCESS);
                htaccessContent = fs.readFileSync(APACHE_HTACCESS, 'utf8');
            }

            // Hapus blok Cyber-X lama (jika ada) agar tidak menumpuk saat update
            const regexBlock = /# BEGIN CYBER-X WAF[\s\S]*?# END CYBER-X WAF\n?/g;
            htaccessContent = htaccessContent.replace(regexBlock, '');

            // Tambahkan blok baru di paling atas atau bawah
            const finalContent = apacheRules.trim() + '\n\n' + htaccessContent.trim();
            fs.writeFileSync(APACHE_HTACCESS, finalContent.trim() + '\n');

            const report = `
✅ *VIRTUAL PATCH APACHE AKTIF!* 🛡️

Aturan keamanan (.htaccess) berhasil ditanam di:
\`${APACHE_HTACCESS}\`

Filter yang diaktifkan:
• Anti File Sensitif (.env, .log)
• Anti Eksekusi Script
• Anti Bad Bots
• Anti SQLi & XSS

_(Apache membaca .htaccess secara real-time, tidak perlu restart server)._`.trim();

            logger.info('[VPATCH] Apache WAF sukses diterapkan ke .htaccess.');
            msg.reply(report);

        } catch (error) {
            logger.error(`[VPATCH-APACHE] Gagal menulis htaccess: ${error.message}`);
            msg.reply(`❌ *Gagal menerapkan WAF Apache:* ${error.message}`);
        }
    }

    // ==========================================
    // 3. VIRTUAL PATCH: NODE.JS
    // ==========================================
    else if (serverType === 'nodejs') {
        const report = `
ℹ️ *INFORMASI WAF NODE.JS* 🛡️

Perisai keamanan (Middleware) untuk ekosistem Node.js Gateway sudah *terintegrasi dan aktif secara permanen* di dalam sistem.

Setiap request yang masuk melalui port API akan disaring dari SQLi, XSS, dan Path Traversal sebelum diproses.

_Status: ON (Berjalan di latar belakang)_`.trim();
        msg.reply(report);
    }
};

// ==========================================
// 4. DEPLOY HONEY-TOKEN (PERANGKAP HACKER)
// ==========================================
const deployHoneyToken = async (msg) => {
    // Gunakan direktori yang sama dengan perlindungan Apache (biasanya root dokumen web)
    const webPath = process.env.PROTECTED_DIR || '/var/www/html';
    const tokenPath = path.join(webPath, 'config_backup_secret.html');
    
    // Ganti dengan IP atau domain Zotac Anda agar tautan penjejak dapat berfungsi dari luar
    const serverIP = process.env.SERVER_IP || '127.0.0.1'; // Pastikan Anda mengatur SERVER_IP di file .env

    const content = `<!DOCTYPE html>
<html>
<head>
    <title>Internal Config Backup</title>
    <link rel="stylesheet" href="http://${serverIP}:3008/assets/css/theme-dark-cache.css">
</head>
<body>
    <h1>Restricted Area</h1>
    <p>Unauthorized access is strictly prohibited. Your IP has been logged.</p>
    <pre>
    API_KEY=hidden_data
    DB_USER=admin_root
    </pre>
</body>
</html>`;
    
    try {
        fs.writeFileSync(tokenPath, content);
        logger.info(`[HONEY-TOKEN] Berhasil ditanam di: ${tokenPath}`);
        msg.reply(`✅ *Honey-Token Deployed!*\nFile umpan telah ditanam di \`${tokenPath}\`.\n\nSiapapun yang membuka file ini akan langsung memicu alarm intelijen!`);
    } catch (err) {
        logger.error(`[HONEY-TOKEN] Gagal menanam token: ${err.message}`);
        msg.reply('❌ *Gagal menanam Honey-Token.* Periksa izin akses direktori web Anda.');
    }
};

module.exports = { handleVirtualPatch, deployHoneyToken };